### ISSUE TITLE
BetterFoliage Nether textures brokn

### ISSUE THREAD

**Issue by zelpa** [yurisuika/Isabella#1]
Certain textures in the Nether break when using this texturepack, specifically the ones that hang from the netherrack. You can see in this image anything behind them is transparent, allowing me to see through walls

![lame](https://i.ggor.ca/crhuGV.png)

**Comment by yurisuika** [comment]
This was probably a bug with the mod.  I updated the BetterFoliage textures but was not able to replicate this either before or after in 1.12.2.
