### ISSUE TITLE
FPS Drop Lag when Destroying/Placing Blocks

### ISSUE THREAD

**Issue by powerswing** [yurisuika/Isabella#3]
Yurisuika,

I see that you've been proactively working on Isabella. This is very good!
However, I don't know why but I have an issue with your texture pack (both v. 1.15 & 1.16 without any custom models, custom maps and mod textures)

Specifically, when I destroy or place a block I experience a lag - the one you usually get when your FPS drops to zero for a second. And it doesn't matter whether I play offline or on a server - the issure remains.

Do you have any thoughts on this and possible workarounds?

Thanks.

**Comment by powerswing** [comment]
Oh,

It seems that Optifine for 1.15 (preview version dated April 1) causes this, as this texture pack works perfectly with 1.14 with Optifine and 1.15 without Optifine.

Okay, this issue may be redundant, but let it stay close until there is a release of Optifine 1.15, so I can test it out.

**Comment by yurisuika** [comment]
Yeah, Optifine is a bit buggy at the moment. It will even stop rendering chunks at 64 view distance, but that is why it isn't officially released yet. I know what you mean about the block lag, but there isn't anything in the basic pack that should cause the block lag.
